### PR TITLE
NH-7758 Added laravel 9 sample app for nosetest framework

### PR DESCRIPTION
**Pull request by jerrytfleung**

### CODE REVIEW

**Review by cheempz — APPROVED** [review]
LGTM

**Comment by cheempz** [comment]
@jerrytfleung the large number of files made the review page freeze, so leaving some minor observations here:

* thanks for the README update!
* there seem to be several `.DS_Store` files that were committed, maybe should remove/gitignore for future

**Comment by jerrytfleung** [comment]
> @jerrytfleung the large number of files made the review page freeze, so leaving some minor observations here:
> 
> * thanks for the README update!
> * there seem to be several `.DS_Store` files that were committed, maybe should remove/gitignore for future

Done!

**Review by cheempz — APPROVED** [review]
reapproved

**Pull request merged**
